cassandra:
  ports:
    - 7000 7000
    - 9042 9042

  healthChecks:
    logPatterns:
      - pattern: Starting listening for CQL clients
        timeout: 1000000

consul:
  ports:
    - 8500 8500
    - 8600 8600

initializer:
  privileged: true
  links:
    - consul
  healthChecks:
    logPatterns:
      - pattern: Container Initialization Complete!
        timeout: 100000

api:
  packaging:
    add:
      - target/dependency/moviebuzz-api.jar
  ports:
    - 8081 8081

  healthChecks:
    pings:
      - url: http://localhost:8081/moviebuzz/actuator/health
        timeout: 90000
  tag: bgosavi/moviebuzz-integration_api:${project.version}
  links:
    - consul
    - cassandra