mzookeeper:
  ports:
    - 2181 2181
  env: {
    "ZOOKEEPER_CLIENT_PORT":"2181"
  }
  sleep: 1000


elasticsearch:
  env: {
    "network.publish_host":"127.0.0.1",
    "transport.host":"0.0.0.0",
    "ES_JAVA_OPTS": "-Xms512m -Xmx512m"
  }
  ports:
    - 9200 9200
    - 9300 9300

  healthChecks:
    logPatterns:
      - pattern: started
        timeout: 100000
  exposeContainerIp: true

cassandra:
  ports:
    - 7000 7000
    - 9042 9042

  healthChecks:
    logPatterns:
      - pattern: Starting listening for CQL clients
        timeout: 1000000

consul:
  ports:
    - 8500 8500
    - 8600 8600

initializer:
  privileged: true
  links:
    - consul
    - elasticsearch
  healthChecks:
    logPatterns:
      - pattern: Container Initialization Complete!
        timeout: 100000

mkafka:
  env: {
    "KAFKA_ZOOKEEPER_CONNECT": "mzookeeper:2181",
    "KAFKA_ADVERTISED_LISTENERS": "PLAINTEXT://mkafka:9092",
    "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR": "1"
  }
  links:
    - mzookeeper:mzookeeper
  extraHosts:
    - "mkafka:127.0.0.1"
  ports:
    - 9092 9092
  sleep: 1000

api:
  packaging:
    add:
      - target/dependency/moviebuzz-api.jar
  ports:
    - 8081 8081

  healthChecks:
    pings:
      - url: http://localhost:8081/moviebuzz/actuator/health
        timeout: 100000
  tag: bgosavi/moviebuzz-integration_api:${project.version}
  links:
    - consul
    - cassandra
    - elasticsearch
    - mzookeeper
    - mkafka

processor:
  packaging:
    add:
      - target/dependency/moviebuzz-process.jar
  ports:
    - 8082 8082

  healthChecks:
    pings:
      - url: http://localhost:8082/moviebuzz/actuator/health
        timeout: 100000
  tag: bgosavi/moviebuzz-integration_processor:${project.version}
  links:
    - consul
    - cassandra
    - elasticsearch
    - mzookeeper
    - mkafka