consul:
  ports:
    - 8500 8500
    - 8600 8600

initializer:
  privileged: true
  links:
    - consul

api:
  packaging:
    add:
      - target/dependency/moviebuzz-api.jar
  ports:
    - 8081 8081

  healthChecks:
    pings:
      - url: http://localhost:8081/moviebuzz/actuator/health
        timeout: 60000
  tag: bgosavi/moviebuzz-integration_api:${project.version}
  links:
    - consul